ktaranov/sqlserver-kit

- SQL Server Name Convention and T-SQL Programming Style.md
- SQL Server Name Convention.md
Added T-SQL programming style recommendations
>  Update and rename SQL Server Name Convention.md 

- Utilities/README.md
added 12 sql server utitlities from EMS
> Edit utilities

- SQL Server Version.md
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Update SQL Server 2012 version information

- SQL Server Version.md
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Add SQL Server 2012 SP3 CU7, SQL Server 2012 SP2 CU16

- Utilities/README.md
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Update info for devart utilities

- Scripts/How_to_Find_Queries_Using_an_Index.sql
How to Find Queries Using an Index
and Queries Using Index Hints
By Kendra Little
> Add SQL scripts

- Scripts/Backup_Restore_What’s_My_Status.sql
http://www.sqlservercentral.com/blogs/the-sql-professor/2017/01/26/backuprestorewhats-my-status/
> Add SQL script backup/restore status

- SQL Server Trace Flag.md
1. Add 3408, 3663, 8009
2. Edit 902, 4022, 8010, 2505, (2520,2588), 3604
3. 2520 and 2588 were united
> Add/edit information for SQL Server Trace Flags (1-10)

- SQL Server Trace Flag.md
1. Add 669, 647, (670, 671), 1165, 1482, 1808, 1816, 3861
2. Edit 3605, 828, 3502, 3504, 3505, 1106, 1117, 1118, 1140, 1806, 1807, 2330
3. 670 and 671 were united
4. Change the TF quantity from 362 to 374 (united counted separately)
> Add/edit information for SQL Server Trace Flags (10-21)

- SQL Server Trace Flag.md
1. Add 15 TF: 9394, 9929, 10202, 10207, 8903, 3917, 3940, 839, 1615, 6531, 8022, 8025, 851, 4620, 8075
2. Edit 15 TF: 830, 3601, 3603, 8002, 8015, 8033, 8049, 834, 836, 840, 845, 3654, 4610, 4618, 8030
3. Change the TF quantity from 374 to 389
> Add/edit information for SQL Server Trace Flags (part 3)

- SQL Server Trace Flag.md
1. Add 19 TF: 3448, 4112, 7311, 7833, 3412, 3924, 3028, 3034, 3035, 3039, 3057,
3210, 3212, 3216, 3660, 9109, 1208, 2456, 8001
2. Edit 26 TF: 4010, 4029, 7300, 706, 8765, 9394, 2537, 3001, 3004,
3014, 3031, 3042, 3117, 3111, 3213, 3236, 3211, 3400, 3422, 3607, 3608, 3609, 1200, 1205, 1206, 1211
3. Change the TF quantity from 388 to 407
> Add/edit information for SQL Server Trace Flags (part 4)

- SQL Server Trace Flag.md
1. Add 33 TF: 274, 2309, 3215, 2318, 2336, 2398, 4101, 4103, 4105, 4106, 4108, 4109, 4110, 4111, 4115, 4117, 4119, 4120,
4124, 4126, 4128, 4129, 4131, 4133, 6530, 7357, 8608, 8609, 8719, 8739, 9348, 9472, 9482
2. Edit 28 TF: 806, 818, 2549, 2558, 2562, 2566, 4199, 4102, 4104, 4107, 4116, 4127, 4135, 212, 698, 2430, 4130, 2363, 2388, 7252, 8612, 8666, 8765, 2301, 2328, 2371, 2389, 2390
3. Change the TF quantity from 407 to 441
> Add/edit information for SQL Server Trace Flags (part 5)

- SQL Server Data Types.md
Add columns:
- SSIS Variables
- OLE DB
- ADO.NET
> Edit SSIS data type mapping table

- PowerShell/Export-AllPlans.ps1
- PowerShell/Truncate-AllTables.ps1
- Stored_Procedure/udp_IntegerListfromRanges.sql
- User_Defined_Function/udf_ConvertRangesInIntegerList.sql
- User_Defined_Function/udf_IntegerListFromRangesFunction.sql
- User_Defined_Function/udf_SecondConvertRangesInIntegerList.sql
1. Add 3 udf and 1 udp Lists With, or Without, Ranges functions
2. Add PS script to export all plans from cache to a .SQLPLAN files
3. Edit Truncate-AllTables.ps1
> Added Lists With, or Without, Ranges functions

- SSMS/SSMS_Addins.md
- Utilities/README.md
1. Add 5 and update 2 SQL Server Utilities
2. Update 1 SSMS/SSMS_Addins.md
> Update SQL Server Utilities (part 1)

- Scripts/UnPivot_Output_Restore_Headeronly.sql
- Stored_Procedure/sp_DBA_job_notification.sql
- Stored_Procedure/sp_SQLskills_ExposeColsInIndexLevels.sql
- Stored_Procedure/sp_SQLskills_helpindex.sql
- Stored_Procedure/sqlg_ParseDiskskpXml.sql
- Utilities/README.md
> Add stored procedures and script

- PowerShell/Add-UserToRole.ps1
- Scripts/Finding_Blocking_Queries.sql
- Scripts/SQL_Server_Fixed_Role_Permissions.sql
- Stored_Procedure/sp_sizing.sql
1. Add 2 sql script - Finding_Blocking_Queries.sql, SQL_Server_Fixed_Role_Permissions.sql
2. Add 1 powershell script - Add-UserToRole.ps1
3. Add 1 stored procedure - sp_sizing.sql
> Add scripts and procedure

- Utilities/README.md
> Fixed some links in Utilities

- SQL Server Data Types.md
Add 4 links in Source link section
Add SQL types links in tables
> Add links in Data Types

- SQL Server Version.md
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Broken link has changed

- Scripts/Table_and_Index_storage_size.sql
> Add script Table and Index storage size in sql server

- Scripts/DynamicallyGenerateDMAStatement.sql
- Scripts/ShredDeadlockGraph.sql
- Scripts/ShredDeadlockGraph_Sample1.xml
- Scripts/ShredDeadlockGraph_Sample2.xml
1. Add ShredDeadlockGraph script and 2 sample: ShredDeadlockGraph_Sample1.xml, ShredDeadlockGraph_Sample2.xml
2. Add ShredDeadlockGraph script
> Add Scripts

- Scripts/MaxServerMemoryCalculator.sql
- Scripts/PowerSavingCheck.sql
1. Max Server Memory Calculator
2. Create power saving check
> Add bornsql scripts

- SQL Server People.md
Deleted Mike Fal double deleted
Rob Sewell country changed, based on MS MVP profile info
> Added a few professionals

- Utilities/README.md
> Add BimlExpress and BIDS Helper utilities

- Stored_Procedure/sp_FailedJobs.sql
- Stored_Procedure/sp_FailedLogins.sql
- Stored_Procedure/sp_RestoreScript.sql
sp_FailedJobs.sql
sp_FailedLogins.sql
sp_RestoreScript.sql
> Add David Fowler's stored procedures

- Scripts/FindDBConnectionLeaks.sql
- Scripts/FindLongRunningJobSteps.sql
- Scripts/ObjectSizes.sql
FindDBConnectionLeaks.sql
FindLongRunningJobSteps.sql
ObjectSizes.sql
> Add 3 sql server scripts

- Scripts/DetermineSpaceWithinSQLDatabaseFiles.sql
- Scripts/FindingImplicitColumnConversionsInPlanCache.sql
- Scripts/GenerateTSQLTimeSlices.sql
- Scripts/MisleadingSQLServerPerformanceCounters.sql
1. DetermineSpaceWithinSQLDatabaseFiles
2. FindingImplicitColumnConversionsInPlanCache
3. GenerateTSQLTimeSlices
4. MisleadingSQLServerPerformanceCounters
> Add 4 SQL script in Scripts

- Stored_Procedure/sp_foreign_key$batch_drop_and_recreate.sql
- Stored_Procedure/sp_ns_shrink_db_log.sql
- Stored_Procedure/usp_generateIdentifier.sql
- sp_foreign_key$batch_drop_and_recreate
- sp_ns_shrink_db_log
- usp_generateIdentifier
> Add to Stored Procedure: FK drop and recreate, Shrink DB, Gen. strings

- SQL Server Version.md
- KB4019094 Cumulative Update 6 for SQL Server 2014 SP2
- KB4019093 Description of the security update for SQL Server 2014 Service Pack 2 GDR: August 8, 2017
- KB4016762 Cumulative Update 10 for SQL Server 2012 SP3
> Add SQL Servers 2014 SP2 CU6 and GDR, 2012 SP3 CU10

- SQL Server Version.md
- KB4019099 Cumulative Update 13 for SQL Server 2014 SP1
> Add SQL Server 2014 SP1 CU13

- PowerShell/Get-CmsHosts.ps1
- PowerShell/Get-SQLUnattendedFile.ps1
- PowerShell/Get-SystemInfo.ps1
- PowerShell/Shred-XElogs.ps1
- Stored_Procedure/sp_ChangeDatabaseOwnerShip.sql
> Add SP ChangeDatabaseOwnerShip

- README.md
- SQL Server People.md
Added info for Solomon Rutzky / Sql Quantum Leap to main README and to "SQL Server People" page.
> Added my info to 2 pages

- Utilities/README.md
1. sqlcmd Utility
2. mssql-cli
3. FlowHeater
> Add 3 tools to Utilities

- Stored_Procedure/sp_BlitzInMemoryOLTP.sql
Added SQL 2014 validation for running on EE, @tableName parameter for getting details on specific table,  display for @debug execution, changed location in script for memory-optimized table types, and modified native modules section to included triggers and functions.
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Validation for EE on SQL 2014, and updated native modules section to include triggers and functions

- Stored_Procedure/sp_BlitzInMemoryOLTP.sql
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Fixed capitalization for @loadedmoduleName, and added logic to handle empty result sets.

- Stored_Procedure/sp_BlitzInMemoryOLTP.sql
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Various cosmetic fixes.

- SQL Server Trace Flag.md
Added some trace flags
Changed trace flag 9288 and 9292 ordering
> Update SQL Server Trace Flag.md

- README.md
update number of members for SQLcom.ru telegram channel
Fixes #
- just updates number of members for SQLcom.ru telegram channel
- tests are NOT required - just minor edits in description
> first try: Update README.md - update number of members for SQLcom.ru telegram channel

- SSMS/SSMS_Addins.md
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Adding new SSMS Add-In to list

- Utilities/README.md
Full Convert Enterprise and Replicator Pro
> Add Spectral Core tools

- Utilities/README.md
Sorry, I made a very stupid typo, breaking URL.
> Fix Replicator Pro URL

- SQL Server Name Convention and T-SQL Programming Style.md
Fix two typos in "General programming style" section.
> Fix typos in SQL Server doc

- SQL Server Trace Flag.md
For memory-optimized TempDB metadata.
> Adding trace flag 3895

- Utilities/README.md
I've updated the information about our products.
Thank you
> Update DBConvert products info

- SQL Server Name Convention and T-SQL Programming Style.md
Add my proposal for object name convention for SQL Server Statistics
Add "_" in IXC prefix
> Add object name convention for Statistics

- SQL Server Version.md
> Update SQL Server Version.md

- README.md
- Utilities/README.md
Add DBA Dash to list of open source projects and utilities #199
> Add DBA Dash

- Utilities/README.md
Added SQLWATCH - Open Source SQL Server Monitoring solution
> Add SQLWATCH Monitoring Solution

- README.md
Add the ansible collection `lowlydba.sqlserver`
> add lowlydba.sqlserver

- README.md
Added SQLWatch.io - an Open Source and completely free SQL Server Monitoring project
> Update README.md: Add SQLWatch.io

- SSMS/SSMS_Addins.md
Hi @ktaranov !  New add-in for your list.
Added SQL Shades, a true dark mode add-in.
Also updated VersionSQL's company name and price, which has changed, and fixed another add-in's anchor tag.
> Add SQL Shades

- SQL Server Trace Flag.md
Query Store on readable secondaries.
> Trace flags - add 12606

- SSMS/SSMS_Addins.md
Поменял SSMS/SSMS_Addins.md, подкорректировав список add-ins
> Added S-R-SSMS-Extension

- SSMS/SSMS_Addins.md
SSMS_Addins.md changed. Поменял дубликат Statistics Reporter SSMS Ext. на SQL Refactor Studio
> Reporter Duplicate changed to SQL Refactor Studio add-in

- SQL Server Trace Flag.md
Added 12618 and 12656. Closes #232.
> #232 trace flags
